swagger: "2.0"
info:
  title: Team Decide - Film page
  description: bla bla bla
  termsOfService: http://swagger.io/term
  version: 1.0.0
host: 127.0.0.1:91
basePath: /
schemes:
  - http
paths:
  /film:
    get:
      summary: Get film list
      parameters:
        - in: query
          name: q
          type: string
          required: false
          description: string key filter
      responses:
        200:
          description: OK
  /film/{id}:
    get:
      summary: Get film details
      parameters:
        - in: path
          name: id
          type: number
          required: true
          description: Numeric ID of the film to get
      responses:
        200:
          description: OK
